# Reads app_config.properties and runs Flutter with the right --dart-define flags.
# Also syncs platform files (web/index.html, ios/AppConfig.xcconfig) from config.
# Usage: .\run_app.ps1 android | chrome | ios

param(
    [Parameter(Position = 0)]
    [ValidateSet("android", "chrome", "ios")]
    [string]$Platform = "android"
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot

& (Join-Path $Root "sync_config.ps1")
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

$configPath = Join-Path $Root "app_config.properties"
$config = @{}
Get-Content $configPath -Encoding UTF8 | ForEach-Object {
    $line = $_.Trim()
    if ($line -and -not $line.StartsWith("#") -and $line -match "=") {
        $parts = $line -split "=", 2
        $config[$parts[0].Trim()] = $parts[1].Trim()
    }
}

if ($Platform -eq "android") {
    if ($config["ANDROID_APP_ID"]) {
        Write-Host "Android applicationId: $($config['ANDROID_APP_ID'])" -ForegroundColor Green
    }
    Write-Host ""
    Write-Host "Android debug SHA-1 (add to Google Cloud Android OAuth client):" -ForegroundColor Cyan
    $keystore = Join-Path $env:USERPROFILE ".android\debug.keystore"
    $keytool = Join-Path "D:\Android Studio\jbr\bin" "keytool.exe"
    if (-not (Test-Path $keytool)) { $keytool = "keytool" }
    if (Test-Path $keystore) {
        try {
            $sha1 = & $keytool -list -v -keystore $keystore -alias androiddebugkey -storepass android -keypass android 2>$null |
                Select-String "SHA1:"
            if ($sha1) { Write-Host $sha1 } else { Write-Host "  (could not read SHA-1)" }
        } catch {
            Write-Host "  (keytool failed - see SETUP_OAUTH.md)"
        }
    } else {
        Write-Host "  (debug.keystore not found - run one Android build first)"
    }
    Write-Host ""
}

function Test-PlaceholderValue {
    param([string]$Value)
    return (-not $Value) -or ($Value -match "YOUR_|REPLACE")
}

$required = @("GOOGLE_WEB_CLIENT_ID", "API_BASE_URL")
foreach ($key in $required) {
    if (Test-PlaceholderValue $config[$key]) {
        Write-Host "Set $key in app_config.properties" -ForegroundColor Red
        exit 1
    }
}

if ($Platform -eq "ios") {
    foreach ($key in @("IOS_BUNDLE_ID", "GOOGLE_IOS_CLIENT_ID")) {
        if (Test-PlaceholderValue $config[$key]) {
            Write-Host "Set $key in app_config.properties for iOS builds." -ForegroundColor Red
            exit 1
        }
    }
}

# iOS: write AppConfig.xcconfig
if ($config["IOS_BUNDLE_ID"] -and -not (Test-PlaceholderValue $config["IOS_BUNDLE_ID"])) {
    $iosClientId = $config["GOOGLE_IOS_CLIENT_ID"]
    $reversedScheme = ""
    if ($iosClientId -and $iosClientId -match "^(.+)\.apps\.googleusercontent\.com$") {
        $reversedScheme = "com.googleusercontent.apps.$($Matches[1])"
    }
    $xcLines = @(
        "// Auto-generated by run_app.ps1 - edit app_config.properties instead"
        "APP_BUNDLE_ID = $($config['IOS_BUNDLE_ID'])"
    )
    if ($iosClientId -and -not (Test-PlaceholderValue $iosClientId)) {
        $xcLines += "GOOGLE_IOS_CLIENT_ID = $iosClientId"
        if ($reversedScheme) {
            $xcLines += "GOOGLE_IOS_URL_SCHEME = $reversedScheme"
        }
    }
    $xcconfig = Join-Path $Root "ios\AppConfig.xcconfig"
    [System.IO.File]::WriteAllLines($xcconfig, $xcLines)
    Write-Host "Wrote ios/AppConfig.xcconfig (bundle: $($config['IOS_BUNDLE_ID']))"
}

$defineFile = switch ($Platform) {
    "chrome" { "dart_defines.web.json" }
    "ios"    { "dart_defines.web.json" }
    default  { "dart_defines.android.json" }
}

$device = switch ($Platform) {
    "chrome" { "chrome" }
    "ios"    { "ios" }
    default  { "android" }
}

Write-Host "Running: flutter run -d $device --dart-define-from-file=$defineFile" -ForegroundColor Green

if ($Platform -eq "chrome") {
    $webPort = $config["WEB_PORT"]
    if (-not $webPort) { $webPort = "8080" }
    Write-Host "Web port: $webPort (add http://localhost:$webPort to Google Cloud origins if not done)" -ForegroundColor Cyan
    flutter run -d $device --dart-define-from-file=$defineFile --web-port=$webPort
} else {
    flutter run -d $device --dart-define-from-file=$defineFile
}
